create table if not exists public.user_overrides (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  deal_id text not null,
  field_name text not null,
  override_value jsonb not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, deal_id, field_name)
);

create index if not exists user_overrides_user_deal_idx
  on public.user_overrides (user_id, deal_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists user_overrides_set_updated_at on public.user_overrides;
create trigger user_overrides_set_updated_at
before update on public.user_overrides
for each row
execute function public.set_updated_at();

alter table public.user_overrides enable row level security;

create policy "Users can view their overrides"
on public.user_overrides
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert their overrides"
on public.user_overrides
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their overrides"
on public.user_overrides
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their overrides"
on public.user_overrides
for delete
to authenticated
using (auth.uid() = user_id);
