create table if not exists public.deals (
  id bigint generated by default as identity primary key,
  deal_id text not null unique,
  owner_user_id uuid references auth.users(id) on delete set null,
  display_name text,
  visibility text not null default 'private' check (visibility in ('private', 'shared', 'public_example')),
  is_example boolean not null default false,
  source text not null default 'upload',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  deal_id text not null references public.deals(deal_id) on delete cascade,
  owner_user_id uuid references auth.users(id) on delete set null,
  file_name text not null,
  mime_type text,
  size_bytes bigint not null default 0,
  sha256 text,
  storage_bucket text not null,
  storage_path text not null,
  source text not null default 'upload',
  created_at timestamptz not null default timezone('utc', now()),
  unique (deal_id, storage_bucket, storage_path)
);

create table if not exists public.pipeline_runs (
  id bigint generated by default as identity primary key,
  deal_id text not null references public.deals(deal_id) on delete cascade,
  owner_user_id uuid references auth.users(id) on delete set null,
  phase text not null,
  status text not null default 'completed',
  cached boolean not null default false,
  message text,
  triggered_by text not null default 'frontend',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.usage_counters (
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  usage_date date not null,
  metric text not null,
  count integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (owner_user_id, usage_date, metric)
);

create index if not exists documents_deal_id_idx on public.documents (deal_id);
create index if not exists pipeline_runs_deal_id_idx on public.pipeline_runs (deal_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists deals_set_updated_at on public.deals;
create trigger deals_set_updated_at
before update on public.deals
for each row
execute function public.set_updated_at();

drop trigger if exists usage_counters_set_updated_at on public.usage_counters;
create trigger usage_counters_set_updated_at
before update on public.usage_counters
for each row
execute function public.set_updated_at();

alter table public.deals enable row level security;
alter table public.documents enable row level security;
alter table public.pipeline_runs enable row level security;
alter table public.usage_counters enable row level security;

create policy "Users can view owned or public deals"
on public.deals
for select
to authenticated
using (owner_user_id = auth.uid() or is_example = true or visibility = 'public_example');

create policy "Users can insert owned deals"
on public.deals
for insert
to authenticated
with check (owner_user_id = auth.uid() or owner_user_id is null);

create policy "Users can update owned deals"
on public.deals
for update
to authenticated
using (owner_user_id = auth.uid())
with check (owner_user_id = auth.uid());

create policy "Users can view owned or public documents"
on public.documents
for select
to authenticated
using (
  owner_user_id = auth.uid()
  or exists (
    select 1
    from public.deals d
    where d.deal_id = documents.deal_id
      and (d.is_example = true or d.visibility = 'public_example')
  )
);

create policy "Users can insert owned documents"
on public.documents
for insert
to authenticated
with check (owner_user_id = auth.uid() or owner_user_id is null);

create policy "Users can view owned pipeline runs"
on public.pipeline_runs
for select
to authenticated
using (owner_user_id = auth.uid() or owner_user_id is null);

create policy "Users can insert owned pipeline runs"
on public.pipeline_runs
for insert
to authenticated
with check (owner_user_id = auth.uid() or owner_user_id is null);

create policy "Users can view own usage counters"
on public.usage_counters
for select
to authenticated
using (owner_user_id = auth.uid());

create policy "Users can insert own usage counters"
on public.usage_counters
for insert
to authenticated
with check (owner_user_id = auth.uid());

create policy "Users can update own usage counters"
on public.usage_counters
for update
to authenticated
using (owner_user_id = auth.uid())
with check (owner_user_id = auth.uid());
